sudo: required

services: 
  - docker

before_install: 
  - docker build -t abhay14kumar/docker-react-app -f Dockerfile.dev .

script: 
  - docker run -e CI=true abhay14kumar/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-452562977747"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"