sudo: required

services: 
  - docker

before_install: 
  - docker build -t abhay14kumar/docker-react-app -f Dockerfile.dev .

script: 
  - docker run -e CI=true abhay14kumar/docker-react-app npm run test